# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'TestCal' do
       pod 'PDTSimpleCalendar', '~> 0.9.1'
end

target 'TestCalTests' do

end

