# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target '333 Project' do
       pod 'PDTSimpleCalendar', '~> 0.9.1'
       pod 'Alamofire', '~> 3.2.1'
       pod 'HTMLReader'
end

target '333 ProjectTests' do

end

target '333 ProjectUITests' do

end

